import os

app_content = (
    "import os\n"
    "from flask import Flask, render_template, jsonify, request\n"
    "from env import BusStopEnv\n"
    "from agent import BaselineAgent, AgentGrader\n"
    "\n"
    "BASE = os.path.dirname(os.path.abspath(__file__))\n"
    "app = Flask(__name__,\n"
    "            template_folder=os.path.join(BASE, 'web', 'templates'),\n"
    "            static_folder=os.path.join(BASE, 'web', 'static'))\n"
    "\n"
    "_env = None\n"
    "_agent = BaselineAgent()\n"
    "_grader = AgentGrader()\n"
    "\n"
    "def get_env():\n"
    "    global _env\n"
    "    if _env is None:\n"
    "        _env = BusStopEnv(difficulty='medium')\n"
    "        _env.reset()\n"
    "    return _env\n"
    "\n"
    "@app.route('/')\n"
    "def index():\n"
    "    return render_template('index.html')\n"
    "\n"
    "@app.route('/api/reset', methods=['POST'])\n"
    "def api_reset():\n"
    "    global _env\n"
    "    difficulty = request.json.get('difficulty', 'medium')\n"
    "    _env = BusStopEnv(difficulty=difficulty)\n"
    "    state = _env.reset()\n"
    "    return jsonify({'state': state.to_dict(), 'step': 0, 'done': False, 'reward': 0})\n"
    "\n"
    "@app.route('/api/state', methods=['GET'])\n"
    "def api_state():\n"
    "    return jsonify(get_env().state().to_dict())\n"
    "\n"
    "@app.route('/api/step', methods=['POST'])\n"
    "def api_step():\n"
    "    env = get_env()\n"
    "    action = request.json.get('action', 'no_action')\n"
    "    result = env.step(action)\n"
    "    report = _grader.grade(env.history)\n"
    "    return jsonify({'state': result.state.to_dict(), 'reward': result.reward,\n"
    "                    'done': result.done, 'info': result.info,\n"
    "                    'score': report.overall_score, 'step': result.info['step']})\n"
    "\n"
    "@app.route('/api/auto_step', methods=['POST'])\n"
    "def api_auto_step():\n"
    "    env = get_env()\n"
    "    action = _agent.act(env.state())\n"
    "    result = env.step(action)\n"
    "    report = _grader.grade(env.history)\n"
    "    return jsonify({'state': result.state.to_dict(), 'reward': result.reward,\n"
    "                    'done': result.done, 'info': result.info,\n"
    "                    'score': report.overall_score, 'step': result.info['step'],\n"
    "                    'action': action})\n"
    "\n"
    "@app.route('/api/grade', methods=['GET'])\n"
    "def api_grade():\n"
    "    env = get_env()\n"
    "    report = _grader.grade(env.history)\n"
    "    return jsonify({'overall_score': report.overall_score,\n"
    "                    'efficiency_score': report.efficiency_score,\n"
    "                    'crowd_control_score': report.crowd_control_score,\n"
    "                    'communication_score': report.communication_score,\n"
    "                    'total_reward': report.total_reward})\n"
    "\n"
    "if __name__ == '__main__':\n"
    "    port = int(os.environ.get('PORT', 7860))\n"
    "    app.run(debug=False, host='0.0.0.0', port=port)\n"
)

docker_content = (
    "FROM python:3.11-slim\n"
    "WORKDIR /app\n"
    "COPY requirements.txt .\n"
    "RUN pip install --no-cache-dir -r requirements.txt\n"
    "COPY . .\n"
    "EXPOSE 7860\n"
    "ENV PYTHONUNBUFFERED=1\n"
    "ENV PYTHONPATH=/app\n"
    "CMD [\"gunicorn\", \"--bind\", \"0.0.0.0:7860\", \"--workers\", \"1\", \"--timeout\", \"120\", \"app:app\"]\n"
)

base = os.path.dirname(os.path.abspath(__file__))

with open(os.path.join(base, "app.py"), "w") as f:
    f.write(app_content)
print("app.py written:", len(app_content), "bytes")

with open(os.path.join(base, "Dockerfile"), "w") as f:
    f.write(docker_content)
print("Dockerfile written:", len(docker_content), "bytes")
